name: timer
description: A Flutter project to implement a simple timer with audio feedback.
publish_to: "none"
version: 0.1.1+1

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.5.0
  flutter:
    sdk: flutter
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/birds.wav
